groups:
  - name: application_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(app_error_count_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: "Error rate is above 10% for the past 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(app_request_latency_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High latency detected
          description: "95th percentile latency is above 2 seconds"

      - alert: HighCPUUsage
        expr: app_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage detected
          description: "CPU usage is above 80% for 5 minutes"

      - alert: HighMemoryUsage
        expr: app_memory_usage_bytes > 1e9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage detected
          description: "Memory usage is above 1GB"

      - alert: HighActiveRequests
        expr: app_active_requests > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: High number of active requests
          description: "More than 100 concurrent requests"